/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowsIndexRouteImport } from './routes/flows/index'
import { Route as SettingsTeamRouteImport } from './routes/settings/team'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as SettingsGuardrailsRouteImport } from './routes/settings/guardrails'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as FlowsNewRouteImport } from './routes/flows/new'
import { Route as FlowsFlowIdRouteImport } from './routes/flows/$flowId'
import { Route as AnalyticsExecutionsExecutionIdRouteImport } from './routes/analytics/executions.$executionId'

const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsIndexRoute = FlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGuardrailsRoute = SettingsGuardrailsRouteImport.update({
  id: '/settings/guardrails',
  path: '/settings/guardrails',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsNewRoute = FlowsNewRouteImport.update({
  id: '/flows/new',
  path: '/flows/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdRoute = FlowsFlowIdRouteImport.update({
  id: '/flows/$flowId',
  path: '/flows/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsExecutionsExecutionIdRoute =
  AnalyticsExecutionsExecutionIdRouteImport.update({
    id: '/executions/$executionId',
    path: '/executions/$executionId',
    getParentRoute: () => AnalyticsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/connectors': typeof ConnectorsRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/flows/new': typeof FlowsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/guardrails': typeof SettingsGuardrailsRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/team': typeof SettingsTeamRoute
  '/flows/': typeof FlowsIndexRoute
  '/analytics/executions/$executionId': typeof AnalyticsExecutionsExecutionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/connectors': typeof ConnectorsRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/flows/new': typeof FlowsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/guardrails': typeof SettingsGuardrailsRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/team': typeof SettingsTeamRoute
  '/flows': typeof FlowsIndexRoute
  '/analytics/executions/$executionId': typeof AnalyticsExecutionsExecutionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/connectors': typeof ConnectorsRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/flows/new': typeof FlowsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/guardrails': typeof SettingsGuardrailsRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/team': typeof SettingsTeamRoute
  '/flows/': typeof FlowsIndexRoute
  '/analytics/executions/$executionId': typeof AnalyticsExecutionsExecutionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/audit-logs'
    | '/connectors'
    | '/flows/$flowId'
    | '/flows/new'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/guardrails'
    | '/settings/integrations'
    | '/settings/team'
    | '/flows/'
    | '/analytics/executions/$executionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/approvals'
    | '/audit-logs'
    | '/connectors'
    | '/flows/$flowId'
    | '/flows/new'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/guardrails'
    | '/settings/integrations'
    | '/settings/team'
    | '/flows'
    | '/analytics/executions/$executionId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/approvals'
    | '/audit-logs'
    | '/connectors'
    | '/flows/$flowId'
    | '/flows/new'
    | '/settings/api-keys'
    | '/settings/billing'
    | '/settings/guardrails'
    | '/settings/integrations'
    | '/settings/team'
    | '/flows/'
    | '/analytics/executions/$executionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  ApprovalsRoute: typeof ApprovalsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  ConnectorsRoute: typeof ConnectorsRoute
  FlowsFlowIdRoute: typeof FlowsFlowIdRoute
  FlowsNewRoute: typeof FlowsNewRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsGuardrailsRoute: typeof SettingsGuardrailsRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  FlowsIndexRoute: typeof FlowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/': {
      id: '/flows/'
      path: '/flows'
      fullPath: '/flows/'
      preLoaderRoute: typeof FlowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/guardrails': {
      id: '/settings/guardrails'
      path: '/settings/guardrails'
      fullPath: '/settings/guardrails'
      preLoaderRoute: typeof SettingsGuardrailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/new': {
      id: '/flows/new'
      path: '/flows/new'
      fullPath: '/flows/new'
      preLoaderRoute: typeof FlowsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId': {
      id: '/flows/$flowId'
      path: '/flows/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof FlowsFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/executions/$executionId': {
      id: '/analytics/executions/$executionId'
      path: '/executions/$executionId'
      fullPath: '/analytics/executions/$executionId'
      preLoaderRoute: typeof AnalyticsExecutionsExecutionIdRouteImport
      parentRoute: typeof AnalyticsRoute
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsExecutionsExecutionIdRoute: typeof AnalyticsExecutionsExecutionIdRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsExecutionsExecutionIdRoute: AnalyticsExecutionsExecutionIdRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  ApprovalsRoute: ApprovalsRoute,
  AuditLogsRoute: AuditLogsRoute,
  ConnectorsRoute: ConnectorsRoute,
  FlowsFlowIdRoute: FlowsFlowIdRoute,
  FlowsNewRoute: FlowsNewRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsGuardrailsRoute: SettingsGuardrailsRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  FlowsIndexRoute: FlowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
